/** 供 app.js 读取；不使用 ES Module，便于 file:// 直接打开预览 */
window.ClubMatchData = {
  clubs: [
    {
      id: "c1",
      tier: "school",
      listCategory: "art",
      name: "光影摄影协会",
      tags: ["#摄影", "#佛系", "#外拍"],
      blurb: "每周一次外拍，期末不卷作品数量。",
      matchReason: "你提到喜欢记录生活与构图，和本社「城市漫游」主题高度契合。",
      summaryKeywords: ["氛围极好", "设备可借", "会议适中"],
      vibeScore: 4.7,
      workload: "中等",
      recruitNeed: "希望新成员有基础审美，愿意参与公众号供稿。",
      gradient: "linear-gradient(145deg, #1e3a5f 0%, #3d2c5c 55%, #7c3aed 100%)",
      reviews: [
        { nickname: "匿名学姐", cohort: "22 级", stars: 5, text: "外拍氛围很轻松，学长会教构图，零基础也能出片。", tags: ["氛围好", "新手友好"] },
        { nickname: "匿名学长", cohort: "21 级", stars: 4, text: "设备能借真的很加分，期末不会催你交一堆作业。", tags: ["设备", "不卷"] },
        { nickname: "路过的猫", cohort: "23 级", stars: 4, text: "例会频率还行，想深度玩需要自己多约拍。", tags: ["会议适中"] },
      ],
      gallery: [
        "linear-gradient(135deg, #312e81, #7c3aed)",
        "linear-gradient(135deg, #1e3a8a, #38bdf8)",
        "linear-gradient(135deg, #4c1d95, #e879f9)",
        "linear-gradient(135deg, #0f172a, #334155)",
      ],
    },
    {
      id: "c2",
      tier: "school",
      listCategory: "tech",
      name: "Python 开发者社",
      tags: ["#技术", "#项目", "#略卷"],
      blurb: "学期内 2 个小项目，适合想写代码的同学。",
      matchReason: "你想系统学 Python，本社有学长带做爬虫与数据分析入门。",
      summaryKeywords: ["干货多", "周末加练", "大佬多"],
      vibeScore: 4.5,
      workload: "偏高",
      recruitNeed: "能每周投入 6h+，完成基础课与小组作业。",
      gradient: "linear-gradient(145deg, #0f172a 0%, #14532d 50%, #22c55e 100%)",
      reviews: [
        { nickname: "码农小王", cohort: "22 级", stars: 5, text: "项目驱动学得很快，但周末确实会有加练，适合真想写代码的人。", tags: ["干货", "略卷"] },
        { nickname: "匿名", cohort: "23 级", stars: 4, text: "学长答疑很及时，组里氛围偏技术宅，社交型可能要适应。", tags: ["技术氛围"] },
        { nickname: "转专业选手", cohort: "21 级", stars: 4, text: "从零到能做小工具，简历上能写真实项目经历。", tags: ["成长快"] },
      ],
      gallery: [
        "linear-gradient(135deg, #052e16, #22c55e)",
        "linear-gradient(135deg, #0f172a, #10b981)",
        "linear-gradient(135deg, #14532d, #86efac)",
        "linear-gradient(135deg, #022c22, #065f46)",
      ],
    },
    {
      id: "c3",
      tier: "school",
      listCategory: "art",
      name: "吉他社",
      tags: ["#音乐", "#路演", "#社交"],
      blurb: "二食堂门口不定期快闪，零基础可入。",
      matchReason: "你在动态里问过吉他社，且标签含「弹唱 / 民谣」。",
      summaryKeywords: ["气氛嗨", "新手友好", "设备共用"],
      vibeScore: 4.8,
      workload: "轻松",
      recruitNeed: "热爱音乐即可，会乐器加分。",
      gradient: "linear-gradient(145deg, #431407 0%, #9a3412 45%, #f97316 100%)",
      reviews: [
        { nickname: "阿哲", cohort: "22 级", stars: 5, text: "路演超嗨，零基础也会有人带和弦，社恐也能先从后勤做起。", tags: ["气氛嗨"] },
        { nickname: "匿名学妹", cohort: "23 级", stars: 5, text: "吉他可以借用，周末练琴房要抢，但整体很治愈。", tags: ["设备共用"] },
        { nickname: "老社员", cohort: "20 级", stars: 4, text: "偶尔活动会晚结束，注意第二天早八（笑）。", tags: ["避雷"] },
      ],
      gallery: [
        "linear-gradient(135deg, #7c2d12, #fb923c)",
        "linear-gradient(135deg, #9a3412, #fdba74)",
        "linear-gradient(135deg, #431407, #ea580c)",
        "linear-gradient(135deg, #78350f, #fcd34d)",
      ],
    },
    {
      id: "c4",
      tier: "school",
      listCategory: "study",
      name: "辩论队",
      tags: ["#表达", "#竞技", "#训练多"],
      blurb: "周中晚训 + 周末模辩，适合想练口才的你。",
      matchReason: "你的 MBTI 为 ENTP，过往标签含「演讲 / 思辨」。",
      summaryKeywords: ["成长快", "赛程密集", "团队协作强"],
      vibeScore: 4.6,
      workload: "高",
      recruitNeed: "能接受高强度备赛与复盘。",
      gradient: "linear-gradient(145deg, #312e81 0%, #1e40af 50%, #38bdf8 100%)",
      reviews: [
        { nickname: "四辩学姐", cohort: "21 级", stars: 5, text: "一年下来表达力明显提升，队友之间关系很铁。", tags: ["成长", "团队"] },
        { nickname: "匿名", cohort: "22 级", stars: 4, text: "训练强度大，期中前后会比较累，要想清楚再入。", tags: ["训练多"] },
        { nickname: "新生杯选手", cohort: "23 级", stars: 5, text: "学长改稿很细，输比赛也会有复盘，不会冷暴力。", tags: ["负责"] },
      ],
      gallery: [
        "linear-gradient(135deg, #1e3a8a, #60a5fa)",
        "linear-gradient(135deg, #312e81, #818cf8)",
        "linear-gradient(135deg, #0c4a6e, #38bdf8)",
        "linear-gradient(135deg, #172554, #6366f1)",
      ],
    },
    {
      id: "c5",
      tier: "city",
      listCategory: "sports",
      listOnly: true,
      name: "邻校 · 羽翼羽毛球社",
      tags: ["#羽毛球", "#联赛", "#训练"],
      blurb: "与同城高校联办友谊赛，固定晚训局，欢迎有基础的同学加入校际积分赛。",
      matchReason: "",
      summaryKeywords: ["赛程多", "场地固定", "跨校交流"],
      vibeScore: 4.4,
      workload: "中等",
      recruitNeed: "每周至少参加 2 次训练，能配合外出比赛日程。",
      gradient: "linear-gradient(145deg, #14532d 0%, #166534 50%, #4ade80 100%)",
      reviews: [
        { nickname: "体特学长", cohort: "21 级", stars: 4, text: "强度比校内社大，但裁判与场地都专业，能交到外校朋友。", tags: ["竞技"] },
        { nickname: "匿名", cohort: "23 级", stars: 4, text: "去邻校打球略折腾，不过水平提升快。", tags: ["通勤"] },
      ],
      gallery: [
        "linear-gradient(135deg, #14532d, #22c55e)",
        "linear-gradient(135deg, #064e3b, #34d399)",
      ],
    },
    {
      id: "c6",
      tier: "city",
      listCategory: "sports",
      listOnly: true,
      name: "同城滑板 & 长板联盟",
      tags: ["#滑板", "#街头", "#夜滑"],
      blurb: "城市广场夜滑、周末刷街，护具与基础教学齐全，零基础可跟练。",
      matchReason: "",
      summaryKeywords: ["社交强", "夜场多", "出片"],
      vibeScore: 4.5,
      workload: "轻松",
      recruitNeed: "自备或租用板面，签署安全须知后可参加活动。",
      gradient: "linear-gradient(145deg, #18181b 0%, #3f3f46 50%, #a855f7 100%)",
      reviews: [
        { nickname: "板仔阿凯", cohort: "22 级", stars: 5, text: "氛围特别 chill，摔了也有人扶（字面意义）。", tags: ["氛围"] },
        { nickname: "路人甲", cohort: "23 级", stars: 4, text: "夏天夜滑很爽，冬天会缩人数。", tags: ["季节"] },
      ],
      gallery: [
        "linear-gradient(135deg, #27272a, #7c3aed)",
        "linear-gradient(135deg, #18181b, #ec4899)",
      ],
    },
    {
      id: "c7",
      tier: "nation",
      listCategory: "tech",
      listOnly: true,
      name: "全国大学生 AI 创新营（示范）",
      tags: ["#AI", "#黑客松", "#路演"],
      blurb: "寒暑假集中营 + 线上沙龙，对接企业与创投导师（演示数据）。",
      matchReason: "",
      summaryKeywords: ["资源顶", "强度高", "简历加分"],
      vibeScore: 4.9,
      workload: "高",
      recruitNeed: "需提交作品小样或 GitHub，通过初筛后入营。",
      gradient: "linear-gradient(145deg, #0c0a09 0%, #1c1917 40%, #f59e0b 100%)",
      reviews: [
        { nickname: "营员", cohort: "全国", stars: 5, text: "导师阵容确实强，熬夜是常态，收获也大。", tags: ["硬核"] },
        { nickname: "观摩", cohort: "线上", stars: 4, text: "直播质量稳定，线下名额难抢。", tags: ["名额"] },
      ],
      gallery: [
        "linear-gradient(135deg, #292524, #f59e0b)",
        "linear-gradient(135deg, #0c0a09, #78716c)",
      ],
    },
    {
      id: "c8",
      tier: "nation",
      listCategory: "service",
      listOnly: true,
      name: "「青行」全国志愿服务联络站",
      tags: ["#志愿", "#支教", "#救灾"],
      blurb: "统筹假期支教与大型活动志愿者招募，证书可录入第二课堂（演示）。",
      matchReason: "",
      summaryKeywords: ["有意义", "流程规范", "证书"],
      vibeScore: 4.6,
      workload: "视项目而定",
      recruitNeed: "需完成线上培训与背景说明，服从排班。",
      gradient: "linear-gradient(145deg, #0c4a6e 0%, #0369a1 50%, #38bdf8 100%)",
      reviews: [
        { nickname: "老志愿者", cohort: "20 级", stars: 5, text: "项目信息透明，不会白干活。", tags: ["靠谱"] },
        { nickname: "匿名", cohort: "22 级", stars: 4, text: "大活动会比较累，但团队后勤跟得上。", tags: ["强度"] },
      ],
      gallery: [
        "linear-gradient(135deg, #075985, #0ea5e9)",
        "linear-gradient(135deg, #164e63, #67e8f9)",
      ],
    },
  ],

  clubListCategories: [
    { id: "all", label: "综合" },
    { id: "art", label: "艺术" },
    { id: "study", label: "学习" },
    { id: "tech", label: "科技" },
    { id: "sports", label: "体育" },
    { id: "service", label: "公益" },
  ],

  searchSuggestions: [
    { type: "club", id: "c3", text: "吉他社" },
    { type: "club", id: "c1", text: "光影摄影协会" },
    { type: "club", id: "c2", text: "Python 开发者社" },
    { type: "club", id: "c4", text: "辩论队" },
    { type: "post", id: "p1", text: "二食堂门口路演" },
    { type: "post", id: "p4", text: "哪个社团不卷" },
    { type: "post", id: "p2", text: "求带入摄影协会" },
  ],

  posts: [
    {
      id: "p1",
      type: "club",
      author: "吉他社",
      linkedClubId: "c3",
      title: "二食堂门口路演进行中",
      body: "距图书馆 200m，欢迎围观点歌～",
      tag: "实时动态",
      hot: true,
      category: "文艺",
      distanceText: "200m",
    },
    {
      id: "p2",
      type: "fresh",
      author: "匿名新生",
      linkedClubId: "c1",
      title: "求带入摄影协会",
      body: "有单反但不敢一个人去招新摊，求学长带！",
      tag: "求助",
      hot: true,
      category: "互助",
      distanceText: "校内",
    },
    {
      id: "p3",
      type: "club",
      author: "Python 开发者社",
      linkedClubId: "c2",
      title: "本学期项目招新预告",
      body: "爬虫 + 可视化，下周宣讲会见。",
      tag: "预热",
      hot: false,
      category: "技术",
      distanceText: "教学楼 A",
    },
    {
      id: "p4",
      type: "fresh",
      author: "小林",
      title: "哪个社团不卷？",
      body: "想参加但怕占用太多时间，求推荐。",
      tag: "讨论",
      hot: false,
      category: "互助",
      distanceText: "—",
    },
    {
      id: "p5",
      type: "club",
      author: "光影摄影协会",
      linkedClubId: "c1",
      title: "本周城市漫游路线",
      body: "老校区梧桐大道，周五 16:00 集合。",
      tag: "活动",
      hot: false,
      category: "文艺",
      distanceText: "1.2km",
    },
    {
      id: "p6",
      type: "club",
      author: "辩论队",
      linkedClubId: "c4",
      title: "新生杯辩题征集",
      body: "你最想辩的话题是？留言区见。",
      tag: "预热",
      hot: false,
      category: "综合",
      distanceText: "活动中心",
    },
  ],

  userProfile: {
    name: "萌新小美",
    mbti: "ENTP",
    zodiac: "天秤座",
    tags: ["摄影", "Python 入门", "民谣弹唱"],
    resume: {
      about: "大一新生，喜欢记录校园生活，也愿意尝试技术类社团；性格外向，想认识志同道合的朋友。",
      interest: "摄影构图、民谣弹唱、用 Python 做一点小工具与小数据分析。",
      skills: "会用手机与入门相机拍摄；Python 基础语法与简单脚本；吉他基础和弦与简单弹唱。",
      expectation: "希望加入氛围开放、对新手友好、任务量适中的社团，能兼顾学业。",
      time: "平日晚上约 2 小时 / 周末半天，可随活动微调。",
    },
  },

  initialChats: [
    { id: "ai", kind: "ai", title: "招新小助手", subtitle: "ClubMatch Bot", last: "试试问我：哪个社团不卷？", pinned: true },
    {
      id: "m1",
      kind: "human",
      title: "吉他社 · 阿哲",
      subtitle: "学长",
      last: "周五路演你来吗？",
      pinned: false,
    },
    {
      id: "m2",
      kind: "human",
      title: "光影摄影协会 · 桃子",
      subtitle: "招新志愿者",
      last: "城市漫游要一起来吗？",
      pinned: false,
    },
  ],

  aiReplies: [
    "根据你的画像，「光影摄影协会」「吉他社」目前匹配度较高；若希望少开会，可优先看标签含「佛系」的社团。",
    "想学 Python 建议关注「Python 开发者社」宣讲会，MVP 演示里可在匹配页右滑收藏。",
    "「不卷」可理解为会议少、任务轻——吉他社、摄影协会在演示数据里 workload 相对友好。",
    "需要我根据你的自我介绍生成一版投递用语吗？在「我的」里可查看 AI 整理后的简历要点。",
  ],
};
